# Generated by Django 6.0.4 on 2026-05-04 23:03

from django.db import migrations, models


def create_missing_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("accounts", "Profile")
    SpotifyProfile = apps.get_model("accounts", "SpotifyProfile")

    for user in User.objects.all().only("id"):
        Profile.objects.get_or_create(user_id=user.id)
        SpotifyProfile.objects.get_or_create(user_id=user.id)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_source',
            field=models.CharField(choices=[('upload', 'Upload'), ('spotify', 'Spotify')], default='upload', max_length=20),
        ),
        migrations.AddField(
            model_name='spotifyprofile',
            name='spotify_avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='spotifyprofile',
            name='spotify_display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='spotifyprofile',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='spotifyprofile',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='spotifyprofile',
            name='spotify_user_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='spotifyprofile',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(create_missing_profiles, migrations.RunPython.noop),
    ]
