# Generated by Django 6.0.4 on 2026-05-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_avatar_image_profile_avatar_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifyprofile",
            name="top_artists_long",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spotifyprofile",
            name="top_artists_short",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spotifyprofile",
            name="top_long_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spotifyprofile",
            name="top_short_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spotifyprofile",
            name="top_tracks_long",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spotifyprofile",
            name="top_tracks_short",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
