# Generated by Django 6.0.2 on 2026-05-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songshare',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
