# Generated by Django 6.0.2 on 2026-05-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def dedupe_songshares(apps, schema_editor):
    SongShare = apps.get_model("feed", "SongShare")
    user_ids = (
        SongShare.objects.order_by()
        .values_list("user_id", flat=True)
        .distinct()
    )
    for user_id in user_ids:
        shares = SongShare.objects.filter(user_id=user_id).order_by("-created_at", "-id")
        keep = shares.first()
        if not keep:
            continue
        shares.exclude(id=keep.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_songshare_caption"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_songshares, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="songshare",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
