# Generated by Django 5.2.14 on 2026-05-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_songshare_one_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songshare',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
